In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries working!")

All libraries working!

In [6]:
jobs = pd.read_csv("C:/Users/riyak/OneDrive/Documents/job-market-intelligence-project/data/raw/adzuna_global_job_listings_2025.csv")
salary = pd.read_csv("C:/Users/riyak/OneDrive/Documents/job-market-intelligence-project/data/raw/DataScience_salaries_2024.csv")

jobs.head()

,job_id,title,company,location_display,location_area,description,created,contract_time,contract_type,salary_min,salary_max,salary_is_predicted,redirect_url,category_label,category_tag,latitude,longitude,adref
0,5427443431,Sr Staff Software Development Engineer - 3D,Vantor,"Herndon, Fairfax County","['US', 'Virginia', 'Fairfax County', 'Herndon']",Vantor is forging the new frontier of spatial ...,2025-10-02T15:03:19Z,NaN,permanent,180859.61,180859.61,1,https://www.adzuna.com/land/ad/5427443431?se=N...,IT Jobs,it-jobs,38.978210,-77.386990,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQyNzQ0MzQzMSIsI...
1,5433149814,Software Development Engineer III,Optimum,"Plano, Madison County","['US', 'Idaho', 'Madison County', 'Plano']",Job Description Are you looking to Optimize yo...,2025-10-05T15:46:29Z,NaN,NaN,137944.83,137944.83,1,https://www.adzuna.com/land/ad/5433149814?se=N...,IT Jobs,it-jobs,43.889435,-111.891487,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQzMzE0OTgxNCIsI...
2,5433137727,Software Development Engineer II,Optimum,"Plano, Madison County","['US', 'Idaho', 'Madison County', 'Plano']",Job Description Are you looking to Optimize yo...,2025-10-05T15:24:10Z,NaN,NaN,133208.16,133208.16,1,https://www.adzuna.com/land/ad/5433137727?se=N...,IT Jobs,it-jobs,43.889435,-111.891487,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...
3,5433152768,Software Development Engineer II,Optimum,"Bethpage, Nassau County","['US', 'New York', 'Nassau County', 'Bethpage']",Job Description Are you looking to Optimize yo...,2025-10-05T15:48:37Z,NaN,NaN,135337.62,135337.62,1,https://www.adzuna.com/land/ad/5433152768?se=N...,IT Jobs,it-jobs,40.744266,-73.482069,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...
4,5323178371,Software Developer/ Engineer,"Athenix Solutions Group, LLC","Savage, Anne Arundel County","['US', 'Maryland', 'Anne Arundel County', 'Sav...",Software Developer/ Engineer Annapolis Junctio...,2025-07-26T07:49:53Z,NaN,NaN,102206.05,102206.05,1,https://www.adzuna.com/land/ad/5323178371?se=N...,IT Jobs,it-jobs,39.132050,-76.799422,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...

In [7]:
salary.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [8]:
print("Jobs dataset shape:", jobs.shape)
print("Salary dataset shape:", salary.shape)

Jobs dataset shape: (17350, 18)
Salary dataset shape: (14838, 11)

In [9]:
print("Jobs columns:")
print(jobs.columns)

print("\nSalary columns:")
print(salary.columns)

Jobs columns:
Index(['job_id', 'title', 'company', 'location_display', 'location_area',
       'description', 'created', 'contract_time', 'contract_type',
       'salary_min', 'salary_max', 'salary_is_predicted', 'redirect_url',
       'category_label', 'category_tag', 'latitude', 'longitude', 'adref'],
      dtype='object')

Salary columns:
Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [10]:
jobs.isnull().sum()

job_id                     0
title                      0
company                    4
location_display           0
location_area              0
description                0
created                    0
contract_time          11702
contract_type          15644
salary_min                 2
salary_max                36
salary_is_predicted        0
redirect_url               0
category_label             0
category_tag               0
latitude                1780
longitude               1780
adref                      0
dtype: int64

In [11]:
salary.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [12]:
jobs = jobs.drop_duplicates()
salary = salary.drop_duplicates()

In [13]:
jobs.columns = jobs.columns.str.lower()
salary.columns = salary.columns.str.lower()

In [14]:
jobs = jobs.drop(columns=['contract_time', 'contract_type'])

In [15]:
jobs['company'] = jobs['company'].fillna('Unknown')

In [16]:
jobs['salary_min'] = jobs['salary_min'].fillna(jobs['salary_min'].median())
jobs['salary_max'] = jobs['salary_max'].fillna(jobs['salary_max'].median())

In [17]:
jobs = jobs.drop(columns=['latitude','longitude'])

In [18]:
jobs.isnull().sum()

job_id                 0
title                  0
company                0
location_display       0
location_area          0
description            0
created                0
salary_min             0
salary_max             0
salary_is_predicted    0
redirect_url           0
category_label         0
category_tag           0
adref                  0
dtype: int64

In [19]:
jobs.head()

,job_id,title,company,location_display,location_area,description,created,salary_min,salary_max,salary_is_predicted,redirect_url,category_label,category_tag,adref
0,5427443431,Sr Staff Software Development Engineer - 3D,Vantor,"Herndon, Fairfax County","['US', 'Virginia', 'Fairfax County', 'Herndon']",Vantor is forging the new frontier of spatial ...,2025-10-02T15:03:19Z,180859.61,180859.61,1,https://www.adzuna.com/land/ad/5427443431?se=N...,IT Jobs,it-jobs,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQyNzQ0MzQzMSIsI...
1,5433149814,Software Development Engineer III,Optimum,"Plano, Madison County","['US', 'Idaho', 'Madison County', 'Plano']",Job Description Are you looking to Optimize yo...,2025-10-05T15:46:29Z,137944.83,137944.83,1,https://www.adzuna.com/land/ad/5433149814?se=N...,IT Jobs,it-jobs,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQzMzE0OTgxNCIsI...
2,5433137727,Software Development Engineer II,Optimum,"Plano, Madison County","['US', 'Idaho', 'Madison County', 'Plano']",Job Description Are you looking to Optimize yo...,2025-10-05T15:24:10Z,133208.16,133208.16,1,https://www.adzuna.com/land/ad/5433137727?se=N...,IT Jobs,it-jobs,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...
3,5433152768,Software Development Engineer II,Optimum,"Bethpage, Nassau County","['US', 'New York', 'Nassau County', 'Bethpage']",Job Description Are you looking to Optimize yo...,2025-10-05T15:48:37Z,135337.62,135337.62,1,https://www.adzuna.com/land/ad/5433152768?se=N...,IT Jobs,it-jobs,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...
4,5323178371,Software Developer/ Engineer,"Athenix Solutions Group, LLC","Savage, Anne Arundel County","['US', 'Maryland', 'Anne Arundel County', 'Sav...",Software Developer/ Engineer Annapolis Junctio...,2025-07-26T07:49:53Z,102206.05,102206.05,1,https://www.adzuna.com/land/ad/5323178371?se=N...,IT Jobs,it-jobs,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTnFIQ1NFR284QkdQY...

In [20]:
jobs['title'] = jobs['title'].str.lower()
salary['job_title'] = salary['job_title'].str.lower()

In [21]:
jobs = jobs.rename(columns={'title': 'job_title'})
jobs.columns

Index(['job_id', 'job_title', 'company', 'location_display', 'location_area',
       'description', 'created', 'salary_min', 'salary_max',
       'salary_is_predicted', 'redirect_url', 'category_label', 'category_tag',
       'adref'],
      dtype='object')

In [24]:
jobs.to_csv("C:/Users/riyak/OneDrive/Documents/job-market-intelligence-project/data/processed/cleaned_data.csv", index=False)